CATS.Test.cats_rank_table_json_data = {
    contests: [
        {
            id: '966412',
            start_date: '07.11.2014 18:00',
            finish_date: '07.11.2014 23:00',
            scoring: 'acm',
            problems: [
                {id: '966427', code: 'A', name: 'Second Best', text_url: '/main.pl?f=problem_text;cpid=966427;sid=;cid=966412', max_points: null},
                {id: '966430', code: 'B', name: 'Customer support', text_url: '/main.pl?f=problem_text;cpid=966430;sid=;cid=966412', max_points: null}
            ]
        }
    ],
    rows: [
        { id: 874939, name: "North Eastern FU",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=874939',
            tm: ['0:18','0:29'],
            td: ['+','+'],
            solved_cnt: 2, penalty: 47, rc: 0,
            place: 1, state: 'ooc', remote: 1,
            t: "Yakutsk"
        },
        { id: 966734, name: "Far Eastern FU: ChubbChubbs",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966734',
            tm: ['0:26','0:40'],
            td: ['+1','+'],
            solved_cnt: 2, penalty: 86, rc: 0,
            place: 2, state: 'ooc', remote: 1,
            t: "Владивосток"
        },
        { id: 910500, name: "Far Eastern S Transport U: 1",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=910500',
            tm: ['0:31','0:59'],
            td: ['+','+1'],
            solved_cnt: 2, penalty: 110, rc: 0,
            place: 3, state: 'ooc', remote: 1,
            t: "Хабаровск"
        },
        { id: 966805, name: "Far Eastern FU: ITeam",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966805',
            tm: ['0:57','0:43'],
            td: ['+1','+'],
            solved_cnt: 2, penalty: 120, rc: 0,
            place: 4, state: 'ooc', remote: 1,
            t: "Vladivostok"
        },
        { id: 966760, name: "Far Eastern FU: Backtrace",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966760',
            tm: ['0:43','1:01'],
            td: ['+1','+'],
            solved_cnt: 2, penalty: 124, rc: 0,
            place: 5, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 966758, name: "MSU 1: Khokhlov",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966758',
            tm: ['1:15','1:16'],
            td: ['+','+2'],
            solved_cnt: 2, penalty: 191, rc: 0,
            place: 6, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 966753, name: "Far Eastern FU: Top Roflers",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966753',
            tm: ['1:02','1:18'],
            td: ['+5','+'],
            solved_cnt: 2, penalty: 240, rc: 0,
            place: 7, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 966808, name: "Far Eastern FU: Darude",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966808',
            tm: ['','1:04'],
            td: ['.','+'],
            solved_cnt: 1, penalty: 64, rc: 1,
            place: 8, state: 'ooc', remote: 1,
            t: "Vladivostok"
        },
        { id: 966811, name: "Far Eastern FU: Darude Sandstorm",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966811',
            tm: ['','1:15'],
            td: ['-5','+'],
            solved_cnt: 1, penalty: 75, rc: 1,
            place: 9, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 966750, name: "Far Eastern FU: Dekalchuk",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966750',
            tm: ['0:57',''],
            td: ['+1','.'],
            solved_cnt: 1, penalty: 77, rc: 1,
            place: 10, state: 'ooc', remote: 1,
            t: "Vladivostok"
        },
        { id: 966774, name: "Far Eastern S Transport U: 2",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966774',
            tm: ['0:58',''],
            td: ['+4','-1'],
            solved_cnt: 1, penalty: 138, rc: 1,
            place: 11, state: 'ooc', remote: 1,
            t: "Хабаровск"
        },
        { id: 966839, name: "Far Eastern FU: Zubarev",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966839',
            tm: ['1:16',''],
            td: ['+5','.'],
            solved_cnt: 1, penalty: 176, rc: 1,
            place: 12, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 966789, name: "Far Easten FU: Pavlenko",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966789',
            tm: ['',''],
            td: ['-9','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: "Vladivostok"
        },
        { id: 966769, name: "MSU 2: Pertsev",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966769',
            tm: ['',''],
            td: ['-8','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: "Владивосток"
        },
        { id: 966778, name: "Far Eastern FU: Samokhin",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966778',
            tm: ['',''],
            td: ['-3','-2'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: "Vladivostok"
        },
        { id: 966771, name: "KoA STU 1",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966771',
            tm: ['',''],
            td: ['-4','-1'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: "Komsomols-on-Amur"
        },
        { id: 966762, name: "Far Eastern FU: Syromiatnikova",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966762',
            tm: ['',''],
            td: ['-4','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 966797, name: "Far Eastern FU: RandomTeam",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966797',
            tm: ['',''],
            td: ['-3','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 956911, name: "r.pankov",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=956911',
            tm: ['',''],
            td: ['-3','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 966813, name: "KoA STU 2",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966813',
            tm: ['',''],
            td: ['-2','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: "Komsomolsk-on-Amure"
        },
        { id: 962626, name: "Far Eastern FU: Nikiforov",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=962626',
            tm: ['',''],
            td: ['-2','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 966786, name: "Far Eastern FU: Bezgodov",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966786',
            tm: ['',''],
            td: ['-1','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: "Артём"
        },
        { id: 966747, name: "Far Eastern FU: Cheburaptory",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966747',
            tm: ['',''],
            td: ['.','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: "Vladivostok"
        },
        { id: 966850, name: "Nikiforov",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=966850',
            tm: ['',''],
            td: ['.','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: ""
        },
        { id: 964759, name: "Far Eastern FU: marshrutka",
            console_url: 'main.pl?f=console;sid=;cid=966412;uf=964759',
            tm: ['',''],
            td: ['.','.'],
            solved_cnt: 0, penalty: 0, rc: 0,
            place: 13, state: 'ooc', remote: 1,
            t: ""
        }
    ]
};